# Generated by Django 5.1.4 on 2024-12-10 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='date_of_birth',
            new_name='fecha_de_nacimiento',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='breed',
            new_name='raza',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='size',
            new_name='tamaño',
        ),
    ]
