# Generated by Django 5.1.4 on 2024-12-10 00:22

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_date_of_birth_pet_fecha_de_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='add_ons',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Ninguno'), (1, 'Cepillado dental'), (2, 'Desenmatado'), (3, 'Tratamiento facial'), (4, 'Masaje corporal'), (5, 'Baño de hidromasaje'), (6, 'Acondicionador de avena y aloe vera')], default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('E', 'Peluquería Express'), ('F', 'Peluquería Completa'), ('P', 'Peluquería Premium Spa')], default='E', max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='tamaño',
            field=models.CharField(choices=[('S', 'Pequeño (Hasta 14 kg)'), ('M', 'Mediano (14 - 23 kg)'), ('L', 'Grande (Sobre 23 kg)')], default='', max_length=20),
        ),
    ]
