# Generated by Django 5.1.4 on 2024-12-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointment_add_ons_alter_appointment_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Peluquería Express', 'Peluquería Express'), ('Peluquería Completa', 'Peluquería Completa'), ('Peluquería Premium Spa', 'Peluquería Premium Spa')], default='E', max_length=40),
        ),
    ]
