# Generated by Django 5.1.4 on 2024-12-10 03:01

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='add_ons',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Ninguno', 'Ninguno'), ('Cepillado dental', 'Cepillado dental'), ('Desenmatado', 'Desenmatado'), ('Tratamiento facial', 'Tratamiento facial'), ('Masaje corporal', 'Masaje corporal'), ('Baño de hidromasaje', 'Baño de hidromasaje'), ('Acondicionador de avena y aloe vera', 'Acondicionador de avena y aloe vera')], default=0, max_length=50),
        ),
    ]
